io: fix path handling on Windows by switching to NtCreateFile
Previously we were using `kernel32.CreateFileW` which had 2 problems:
* No way to provide a dir_fd, so we were always opening `basename(path)`,
  causing us to ignore paths!
* Didn't check if the file exists (so `tigerbeetle format` would overwrite
  files).

Switch to vendoring Zig's OpenFile, which uses `ntdll.NtCreateFile` and has
neither of these issues. Vendoring was required, since we need to pass in
file attributes, which the Zig implementation didn't allow for by default.

Before:
```
~/g/t/tigerbeetle-7> ./tigerbeetle.exe format --replica-count=1 --cluster=0 --replica=0
info(io): creating "foo"...
info(io): allocating 1.06298828125GiB...
info(main): 0: formatted: cluster=0 replica_count=1

~/g/t/tigerbeetle-7> ./tigerbeetle.exe format --replica-count=1 --cluster=0 --replica=0
info(io): creating "foo"...
info(io): allocating 1.06298828125GiB...
info(main): 0: formatted: cluster=0 replica_count=1

~/g/t/tigerbeetle-7> rm foo

~/g/t/tigerbeetle-7> ./tigerbeetle.exe format --replica-count=1 --cluster=0 --replica=0 /tmp/foo
info(io): creating "foo"...
info(io): allocating 1.06298828125GiB...
info(main): 0: formatted: cluster=0 replica_count=1

~/g/t/tigerbeetle-7> ls -l foo
.rw-r--r-- 1.1G federico  8 May 20:43 foo
```

After:
```
~/g/t/tigerbeetle-7> ./tigerbeetle.exe format --replica-count=1 --cluster=0 --replica=0 /tmp/foo
info(io): creating "foo"...
info(io): allocating 1.06298828125GiB...
info(main): 0: formatted: cluster=0 replica_count=1

~/g/t/tigerbeetle-7> ./tigerbeetle.exe format --replica-count=1 --cluster=0 --replica=0 /tmp/foo
info(io): creating "foo"...
error: PathAlreadyExists

~/g/t/tigerbeetle-7> ls -l /tmp/foo
.rw-r--r-- 1.1G federico  8 May 20:44 foo
```