docs: Add --security-opt seccomp=unconfined to Docker commands
Docker 25.0.0 and newer blocks io_uring by default using seccomp: https://github.com/moby/moby/pull/46762

TigerBeetle has no epoll fallback so it fails to start:

```
❯ docker run -v /data -it --rm ghcr.io/tigerbeetle/tigerbeetle \
    format --cluster=0 --replica=0 --replica-count=1 /data/0_0.tigerbeetle
info(io): creating "0_0.tigerbeetle"...
info(io): allocating 1.06298828125GiB...
error: PermissionDenied
```