CI: Fetch tags on release job
So that we don't fail with:

```
fatal: malformed object name HEAD^
unable to spawn the following command: ExitCodeFailure
git tag --merged HEAD^ --sort=-committerdate --list [0-9]*.[0-9]*.[0-9]*
error: the following build command failed with exit code 1:
```